### ISSUE TITLE
Importing WeakAuras from chat

### ISSUE THREAD

**Issue by Aemrodd** [skylerh15/WeakAuras-Cata#1]
## Describe the bug

When trying to send a WeakAura (or group), you can't import it. Even though both accounts use the latest version of WeakAuras, it doesn't work. With 3.3.5a it was usually the case when both accounts used different versions of WeakAuras.

### To Reproduce

1. Be in the same group as the other account.
2. Paste any WeakAura in the chat by shift-clicking it.
3. On the other account, click on the link in the chat and try to import it. It will bug out.

**Screenshots**
![WoWScrnShot_091621_173633](https://user-images.githubusercontent.com/58418019/133642223-6edc7e63-2023-400f-a7e3-19465098bf46.jpg)

**Which version of WeakAuras are you using?**
3.2.3, latest upload on GitHub

**Comment by skyler-code** [comment]
This is a conflict with another addon. I am trying to narrow down where the conflict is, but struggling atm.

**Comment by skyler-code** [comment]
@Aemrodd can you try updating your Details? I found a conflict with the included AceComm lib there so I set that to the 4.3 version

**Comment by Aemrodd** [comment]
I am so sorry, I was absent and didn't get a notification that you responded. Yes, it's working! Thank you so much!
