### ISSUE TITLE
Rapture could not be tracked.

### ISSUE THREAD

**Issue by Ymirhen** [skylerh15/WeakAuras-Cata#2]
## Describe the bug
I tried creating a rapture ICD by observing Rapture effect from combat log, using "Energize" flag from "Combat Log". Since Rapture has a cooldown of 12 seconds, I did use "Timed" hide event with 12 seconds. I get the trigger, but the bar I prepared does not show.

##Error Logs

```
3x 
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:101: attempt to call upvalue "GetSpellName" (a nil value)
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:101: in function <Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:80>
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:127: in function "UpdateSpells"
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:135: in main chunk

Locals:
_ = nil
event = nil
UpdateBook = <func> @WeakAuras\Libs\..\LibSpellRange-1.0.lua:80
Lib = <table> {
 updaterFrame = <unnamed> {}
 spellsByName_spell = <table> {}
 isNumber = <table> {}
 spellsByName_pet = <table> {}
 spellsByID_spell = <table> {}
 spellsByID_pet = <table> {}
 strlowerCache = <table> {}
```
```
5x
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:440: attempt to call upvalue "GetSpellName" (a nil value)
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:440: in function <Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:437>
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:468: in function <Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:462>
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:723: in function "init"
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:960: in function "initialOnUpdate"
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:1004: in function <Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:998>

Locals:
spellList = <table> {
 1 = 28880
}
itemList = <table> {
 25 = <table> {}
 35 = <table> {}
 15 = <table> {}
 8 = <table> {}
 45 = <table> {}
 5 = <table> {}
 10 = <table> {}
 20 = <table> {}
 40 = <table> {}
 80 = <table> {}
 60 = <table> {}
 30 = <table> {}
}
interactList = <table> {
 3 = 8
 2 = 9
 4 = 28
}
res = <table> {}
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
sid = 28880
name = "Gift of the Naaru"
_ = "Racial"
_ = "Icons\Spell_Holy_HolyProtection"
_ = 0
_ = false
_ = 0
_ = 0
minRange = 0
range = 40
GetSpellInfo = <func> =[C]:-1
findSpellIdx = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:437
MeleeRange = 5
addChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:449
checkers_SpellWithMin = <table> {}
checkers_Spell = <table> {}
pairs = <func> =[C]:-1
GetItemInfo = <func> =[C]:-1
checkers_Item = <table> {}
next = <func> =[C]:-1
checkers_Interact = <table> {
 2 = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:398
 3 = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:398
 4 = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:398
}
```

### To Reproduce

1. Create the same trigger and weakaura. To save time, the WA string is below.

<details>
<summary>Click to see the string</summary>

> _!WA:2!vwvZUTXnqyVqaPnQffooPb1fPTUgjbjToPn2Ob9V0aVYRSuIIK7k54KGaSM7skTSz1YfKCLT8Ti0d(SU3l6CpPhGwa)eqi0ZTa(bOh8tqhYDTusGZHsajmZWHdN5BM9JwLxO7c4fWh(1Jeji(l2HILHF4iAalUjlLhqUYC89B0UTGiT49ZfgJIdcz8Ty0yPFjN6TCCNyoTltIKuwSvYfEn9hXWe713UvJt8rbVOdNLgJlXIy8hybRbsoTthcx8bxNNlE48UXOUerrEQGuhK2DycBpcVv)eI1qukhz2(JhVbThnMSuzkNyNgtL(jrO(e(am4I(Mx(oR6s6rILJkX66JKlvJ15yrQVX2wCsB6(Un3YPwnBje6HbgNIyDMa3RNiHefzU9bgXQyrXJnByGMTH7l0440CB3PXUzABi2d9CQ74Uz1N5mct8btAN4vCQTv5TRnCA85UOezkNmmnohakMCbuGK2J0ktxJG)(CM(IxGb5kaRtGgaHhJIEmGEq1(0HOyAxtHFxxHeXLLpIGeKMsojUJm8DulAhZIjtofE80vnxqGWIfd0UQtq1k2Dr04YQVeoGAf1Tu3w9vQv8BtJPIW308aFepRzw5()7FOx)ji8361)uOau3cKuFDKWJmdfzdrp1AeavUKoqwiE2Lvlow3vHq5b)o8Js(CjzFPN5V2moutEjEsAxaR5KaQUylmCQllFTKK5nAIqeMT30zRchNzLe12mTQoFYfnwqPsMgOcmd82RdQNKDz09jyJXxojBm)P5t9hz2)xsfsA7(QZLC1ZidXqU1ffnljTulYH6u7vYcVsg(KSGwyKX2So6W84fltMVmNEWs)CkcdGhAPwTYZN8JA9AXlpjVYCzzzp4Y9Ji7oXOThJJ3HJsgStUWKP3IUDBxhgjYXVx5l7rvRdZUE1Ck3kzXZOwZe8RN21NWt(03w)ktZA2v2KEa5Mj38T5pUp8PnnWtgYjIqweUFYNCg(A4qmJVUTJym(Hxuzxq9TlFTy13z68QVxDE1pO(r19EP6NSu3xDoyODDvjdmR2q5O28kZPQQEGQYUQhnoRyDRUzLwQhQQPCxuv26mQ74Cb1k9M4dWjH7Xmq)7DQAgeUkmgRwCi07ZmFu(UZA1hNB50E14CDcUdj5s2r0doaXXlTbfb8rlTjGeN6HaqWp7Wlbf8zKGIPjOgne)VrJhYBSDRAvR7ObLsnQ7LrWRrj31amrTdWeesODcL3ZoIHWpEOMcmicje76lrra53LD7MgjPfDnwVUVGg3jI4VLBvNMTuHfTbMVGlBeGsrlCSHAWgomwt1T66BSrY8qCxhR)GJGj4hH2p0Dp9hM)677d8vTPDkY1CKa)XDvFrr1DkAd8tYIJ0KzuJ9IVzmOXHJ4gohdrCoLJTMwD3jaNa04AKKD0HgUwbftCntfVk51tSwnLIhJRSvNY3i9fB)n3zSz3kzWcx3pa68bN2eZ3LIXKy36op2XnlATY8l5gv184TrbKNxcb8lXDSr8NVD1Bnt7wnnpOAow4ijlOxgL)7(BrltXQRoUnhEibi6bUIcUOOKquHtYgflR3rxV(nl564u3(agRRv279LMooYPX6qschZ4uOhAEFyuLgUvFwJ6TwV2ymvOFCTkaljlplH16IN3u)uMxfwuFV83YgtJZgeHWuC4mg4ZTGWDTBV6TxBHE)1t(Vp_

</details>

2. Apply Power Word: Shield and make sure it's either dispelled or broken in combat.
3. Ensure that you are trying this on a Priest, as the skill only works on priests.

**Screenshots**
![image](https://user-images.githubusercontent.com/53862217/133905483-33bf8d00-c334-4d1d-b477-6d30612be7a0.png)
Combat log trigger
![image](https://user-images.githubusercontent.com/53862217/133905521-67df8d18-ef8d-4ef8-8236-5ce792cf8b69.png)
Combat log mana and spell specification
![image](https://user-images.githubusercontent.com/53862217/133905591-04d8ccdd-5527-4f60-aa17-783e0094f5fd.png)
Event confirmation

**Which version of WeakAuras are you using?**
WeakAuras 2.3.2, the latest version.

**Comment by skyler-code** [comment]
Please use the latest [release](https://github.com/skylerh15/WeakAuras-Cata/releases/download/3.2.3/WeakAuras-Cata.zip)

**Comment by Ymirhen** [comment]
I meant to write 3.2.3, I messed up the numbers ^^'

Edit: Although, after downloading from the link, both problems have solved! Thank you very much!
