### ISSUE TITLE
Rage bar for warrior does not work.

### ISSUE THREAD

**Issue by Ymirhen** [skylerh15/WeakAuras-Cata#3]
## Describe the bug
A simple rage bar. I wanted to observe the rage status in a progress bar. I tracked rage with "Player/Unit Info" -> "Power" -> "Player" -> "Rage" trigger. However, it does not update in real time. It does not update at all.

**Do you have an error log of what happened?**

```
//Taken from bugsack
6x
 
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:101: attempt to call upvalue "GetSpellName" (a nil value)
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:101: in function <Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:80>
Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:127: in function <Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:126>

Locals:
_ = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_ENTERING_WORLD"
UpdateBook = <func> @WeakAuras\Libs\..\LibSpellRange-1.0.lua:80
Lib = <table> {
 strlowerCache = <table> {}
 spellsByID_spell = <table> {}
 spellsByID_pet = <table> {}
 IsSpellInRange = <func> @WeakAuras\Libs\..\LibSpellRange-1.0.lua:151
 SpellHasRange = <func> @WeakAuras\Libs\..\LibSpellRange-1.0.lua:209
 spellsByName_pet = <table> {}
 updaterFrame = <unnamed> {}
 spellsByName_spell = <table> {}
 isNumber = <table> {}
}
```
```
//Taken from bugsack
492 (and still is counting upon login) x 
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:440: attempt to call upvalue "GetSpellName" (a nil value)
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:440: in function <Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:437>
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:692: in function "init"
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:950: in function "initialOnUpdate"
Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100098.lua:1004: in function <Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:998>

Locals:
self = <table> {
 initialOnUpdate = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:949
 GetFriendMaxChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:776
 GetSmartChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:839
 getRangeAsString = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:657
 GLYPH_ADDED = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:892
 checkerCache_Spell = <table> {}
 findSpellIndex = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:646
 GetFriendMinChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:755
 init = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:667
 GetMiscChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:811
 GLYPH_REMOVED = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:896
 scheduleInit = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:970
 RegisterCallback = <func> @AtlasLoot_Loader\Libs\..\CallbackHandler-1.0.lua:118
 GetMiscMaxChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:790
 GetHarmCheckers = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:743
 MeleeRange = 5
 GetFriendCheckers = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:738
 activate = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:980
 GetFriendChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:797
 callbacks = <table> {}
 GLYPH_UPDATED = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:900
 GetMiscMinChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:769
 UnregisterAllCallbacks = <func> @AtlasLoot_Loader\Libs\..\CallbackHandler-1.0.lua:202
 LEARNED_SPELL_IN_TAB = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:880
 miscRC = <table> {}
 UnregisterCallback = <func> @AtlasLoot_Loader\Libs\..\CallbackHandler-1.0.lua:181
 harmRC = <table> {}
 frame = <unnamed> {}
 GetRange = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:853
 checkerCache_Item = <table> {}
 initialized = true
 GetSmartMaxChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:828
 PLAYER_TALENT_UPDATE = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:888
 getRange = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:853
 GetHarmChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:804
 friendRC = <table> {}
 UNIT_INVENTORY_CHANGED = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:904
 OnEvent = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:874
 processItemRequests = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:910
 GetMiscCheckers = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:748
 GetSmartMinChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:818
 GetHarmMaxChecker = <func> @WeakAuras\Libs\..\LibRangeCheck-2.0.lua:783
 CHARACTER_POINTS_CHAN
```

### To Reproduce

1. Apply the weak aura on a warrior. To save time, here is the weak aura string.
<details>
<summary>Click to expand</summary>

_!WA:2!1v1ZUTXntClOV8LaHGah340VwN2MA0gGEXnv5pOxsZNwfPyLOiPsTojoiasCxsTlRxrYWLRKTVvHEiN19EO6Cpj0hGa)eSqOpb(qFa8tqhYDLDsqYcyRzgoZW5V)yH6RnCnYAKx)9ZILy1EpJr0HRFKLU9GbXu9ZlOoiJA73uDL)70gV5)phZ9dfQocgx7vTwl3AOfwlqcnwZe8cYl)o8prqOov2XTTc7B4JVlkwJv6somotxYBa8tCyPjAfliGQIV0nu5KV(tNW00HTWdPGttIP9cOCQI53numUnV)I3H94y7pvfIiIymhXbZIln1yMFeoooCQumMQ0hiPfNyKgI5K(lmuNEq)zeQxYGbUaTA7An7uFNMwnmotrXrddDm65KaH(XXjE0ruUUlybB)59QwPRBVUUvqUZ0HG26DaT8GCnGQrwnrDm3u618Kr4dOQJnU(mv7FKHFzk3FsSKgf1GKNeCPFdsOJkHdvJRyKOOVkHPOwFAI4(20YeA9pn26OOqSH62PwZMtt45v2sYlBAgJOUz8ME0FUYmMVG3ZxejupQi8Dc0IPkoo6PqBb6C7ofZzdTn17MwQE6goCbNEefht7QvuEGo88lijkRg9m1jvmfCjjEIrhtiMw2ziMXbBtlNERZNE707KExG8IVVKjEyv1SiPqHIqBjgRnEMg(2ZN7wygKOiAGzU6rxnDJ5yqjW0EWFJM7jueQQxm7q66lYzYgFldNNUXuW4mXhLF6zj)X5sgXIzEr0(lDgLeqLR6eXo8qSICDxyCtZKl9UWgwfF9)t(1A6(6E2)nqOGQwpzpnBimSPO(mt5S40tvzZVvkx1YfhIHP3SmVaK5hNjLgnWUXLEb5NyLGt0ctRW3U06ubypj7Yy7tjwH)6ISCD3SAvHJSN)ljXA2GdspN8B(aribITH4OZcYcPBOGQKrl5AVve(8mNwCMv2zLTP5(JRLRwxXo86)CcMa9n81DDLF3hRMqoawWy(2DbynoICW7Cz5zW1wzXPE3UH2Eh3MnAvlt6yOd8mfwo5z5ez57Y(xE99TqVoQrRw1q9YWWKF5hl2Y4ki)SpGczeETsg6rvNfCDHbUFiV6NxOki)IpG9krcNy3uqdIec1)SiismUUzXMY9pOZ)5MBv(ozDaZbg8HhgLpE0FIrKPoG6a98Ozg2M2TW1NBOx23NgS0eyxA77)xxX(v0Xio0EHUHm)94044IwdxgYwM8kw69TUPRpoIw0s2KbwCz7T6yh(d9cPSGq9x5ejWK6oM1URIgMa7hLCaSm)RMoUeYIfBOaGXiaGYqESDL2byjgKOYvEWdKRc5AfIzALsOKNG3pCtgrHWbuhSYXGufEIh2FVaBn80fMcVVHmE4mLfGWoYKJpSa2FGSQT0(IujlYxxrIYNETvMAHbJzekc14HB7o9STVZLb(4cnXefvUEvd0nq9Yh22bMeFz3ovqpEUvNTT1I7P0z6ozjIr2tTvpDHX5qHyybKvA4mTWFugy7f(9OChXiekh1Q2tRHojRzuxbVpyshVUvr1Q1A(aJaadg2ZkIgBw()TlIWrYqCrpizgWckPyCJNPHLtyK5pwYF0lo8vnE8UO5cfd6dwq7zB3g14fTB5wP5mdWnZwE(8BG8dP(7vp9sf3ui38NUhAeokHU5pEZjJWkgg2Vq23qv(WJQbuWI0)O)ePsinVRAWO362BzMuMZ4zd)GFlP2pFqBTy0T2Q8w3ATr)9Z)3d_

</details>

2. Initiate combat and gain rage.
3. The bar does not update as it should. But when viewed in /wa panel, bar shows the rage amount at the time the panel was opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/53862217/133906523-371de9a2-381d-4ebb-a840-8b3894bcb85d.png)
Bar when not in combat and has 0 rage.
![image](https://user-images.githubusercontent.com/53862217/133906542-90ebdd19-6444-4599-9afc-d2cc816554a0.png)
Inconsistency between player's rage and the bar itself.
![image](https://user-images.githubusercontent.com/53862217/133906551-3fff8c4f-0ed0-414a-b340-2bc89527550c.png)
Weak auras panel is opened, and the rage amount is correctly showing once more.

**Which version of WeakAuras are you using?**
Weak auras 3.2.3, the latest version

**Comment by skyler-code** [comment]
![image](https://user-images.githubusercontent.com/23067226/133909425-6499b2fa-6157-4985-b9bc-bcc2c5ad4a5a.png)
Somehow it's loading an incorrect version of LibSpellRange and LibRangeCheck. The current version on this repo was updated to make use of the Cata function GetSpellBookItemName

**Comment by skyler-code** [comment]
Please use the latest [release](https://github.com/skylerh15/WeakAuras-Cata/releases/download/3.2.3/WeakAuras-Cata.zip)
