### ISSUE TITLE
[Enhancment] - Smooth Progress

### ISSUE THREAD

**Issue by maphex** [skylerh15/WeakAuras-Cata#5]
Would it be possible to integrate the Smooth Progress into the back-ported version? Or is this a limitation due to the old client? here is a clip of the integration of it in version 2.4.15:
https://www.youtube.com/watch?v=uZoAnyPNk5M&t=196s&ab_channel=InfusonWoW

**Comment by skyler-code** [comment]
Added thanks to Bunny67!
