### ISSUE TITLE
Unable to cast abilites from spellbook

### ISSUE THREAD

**Issue by maphex** [skylerh15/WeakAuras-Cata#7]
When selecting an ability from spellbook i get a LUA error screenshot below.

This is using the latest clone from the current Git.

![image](https://user-images.githubusercontent.com/12422614/147896324-5de9f533-e798-4d47-89ff-06d4eb2515a0.png)

**Comment by skyler-code** [comment]
Fixed with https://github.com/brues-code/WeakAuras-Cata/commit/89c8078b35b07f6271330df66ec6a9c226425b1e
