### ISSUE TITLE
Aura with only show if spell is not on cooldown doesn't work

### ISSUE THREAD

**Issue by fab1yo** [skylerh15/WeakAuras-Cata#8]
Hey,

I tried to create an aura that only triggers (show) when the spell is not on cooldown. But for any reason it's not working properly. The aura always shows up, even the spell is on cooldown.

I tried it with a condition but it's also not working.

[Aura.txt](https://github.com/brues-code/WeakAuras-Cata/files/7828581/Aura.txt)

**Comment by Aemrodd** [comment]
Oh yeah, I noticed that too, but only with the Feral's Mangle

**Comment by skyler-code** [comment]
Fixed in https://github.com/brues-code/WeakAuras-Cata/commit/ed2dfb1b9c60cd076c9a777d10ac056f6b4e0559
You'll have to go into the trigger and enable "Exact Spell Match"
![image](https://user-images.githubusercontent.com/23067226/148817810-ea84b363-bd45-451a-9249-7d3f2707f9f3.png)
